

CREATE TABLE sys_user(
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME DEFAULT NOW(),
	Mtime DATETIME DEFAULT NOW(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	UserName TEXT(50) NOT NULL,
	NickName TEXT(50) NOT NULL,
	PasswordHash VARCHAR(256) NOT NULL,
	PhoneNumber VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	UserType int NOT NULL
)

CREATE TABLE sys_userprofile(
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME DEFAULT NOW(),
	Mtime DATETIME DEFAULT NOW(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	UserName TEXT(50) NOT NULL,
	NickName TEXT(50) NOT NULL,
	PhoneNumber VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	UserType int NOT NULL,
	Gender INT NOT NULL DEFAULT 2,
	HeadImgUrl VARCHAR(32),
)

CREATE TABLE sys_role(
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME DEFAULT NOW(),
	Mtime DATETIME DEFAULT NOW(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	Name VARCHAR(50) NOT NULL,
	DisplayName TEXT(50) NOT NULL
)

CREATE TABLE sys_user_role(
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	UserId VARCHAR(32) NOT NULL,
	RoleId VARCHAR(32) NOT NULL
)

CREATE TABLE pic_relate
(
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME DEFAULT NOW(),
	Mtime DATETIME DEFAULT NOW(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
TableName varchar (50) NOT NULL,
MasterId varchar (32) NOT NULL,
PicResourceId varchar (32) NOT NULL,
Category varchar (30) NOT NULL,
SortIndex int NOT NULL,
Title nvarchar (100) NOT NULL
)

CREATE TABLE pic_resource
(
Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME DEFAULT NOW(),
	Mtime DATETIME DEFAULT NOW(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
PicType varchar (20) NOT NULL,
PicName varchar (100) NOT NULL,
Width int NOT NULL,
Height int NOT NULL,
PicSize decimal (15, 2) NOT NULL,
PicUrl varchar (256)NOT NULL
) 

CREATE TABLE sys_log(
Id INT PRIMARY KEY NOT NULL auto_increment,
Ctime DATETIME DEFAULT NOW(),
CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
LogType VARCHAR(20) NOT NULL,
Url VARCHAR(1024) NOT NULL,
Ip VARCHAR(30) NOT NULL,
Description Text NOT NULL
)
