

CREATE TABLE [SYS.USER](
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME2(7) DEFAULT GETDATE(),
	Mtime DATETIME2(7) DEFAULT GETDATE(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	UserName NVARCHAR(50) NOT NULL,
	NickName NVARCHAR(50) NOT NULL,
	PasswordHash VARCHAR(256) NOT NULL,
	PhoneNumber VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL
)

CREATE TABLE [SYS.USERPROFILE](
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME2(7) DEFAULT GETDATE(),
	Mtime DATETIME2(7) DEFAULT GETDATE(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	UserName NVARCHAR(50) NOT NULL,
	NickName NVARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Gender INT NOT NULL DEFAULT 2,
	HeadImgUrl VARCHAR(1024),
)

CREATE TABLE [SYS.ROLE](
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	Ctime DATETIME2(7) DEFAULT GETDATE(),
	Mtime DATETIME2(7) DEFAULT GETDATE(),
	CreatedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	ModifiedBy VARCHAR(32) NOT NULL DEFAULT '-1',
	Name VARCHAR(50) NOT NULL,
	DisplayName NVARCHAR(50) NOT NULL
)

CREATE TABLE [SYS.USERROLE](
	Id VARCHAR(32) PRIMARY KEY NOT NULL,
	UserId VARCHAR(32) NOT NULL,
	RoleId VARCHAR(32) NOT NULL
)